imports:
    - { resource: light_config.yml }
    - { resource: bundle/sonata_admin.yml }
    - { resource: bundle/sonata_block.yml }
    - { resource: bundle/sonata_media.yml }
    - { resource: bundle/sonata_formatter.yml }
    - { resource: bundle/sonata_seo.yml }
    - { resource: bundle/stof_doctrine_extensions.yml }
    - { resource: bundle/sylius_resource.yml }
    - { resource: bundle/fos_user.yml }
    - { resource: bundle/rid_image.yml }
    - { resource: bundle/snc_redis.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/heavy_routing.yml"
    templating:
        assets_version: %assets_version%

twig:
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'

assetic:
    bundles: [ AppMainBundle, AppAdminBundle ]
    ruby: %ruby_dir%
    sass: %sass_dir%
    java: /usr/bin/java
    write_to: %kernel.web_dir%
    read_from: %kernel.web_dir%

    filters:
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

#        compile with ruby gem
        scss:
            apply_to: "\.(scss|sass)$"

#        compile with scssphp lib: "leafo/scssphp": "0.0.7"
#        scssphp:
#            apply_to: "\.scss$"

#        compile with lessphp lib: "leafo/lessphp": "0.3.9"
#        lessphp:
#            apply_to: "\.less$"
#            # Formatter options: compressed, lessjs, classic
#            formatter: "classic"
#            preserve_comments: false
#            presets:
#                my_variable: "#000"
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        types:
            rid_image: Rid\Bundle\ImageBundle\DBAL\Types\RidImageType
            rid_file: Rid\Bundle\ImageBundle\DBAL\Types\RidFileType
        mapping_types:
            rid_image: rid_image
            rid_file: rid_file
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

rid_page:
    template:
        layout: AppMainBundle::layout.html.twig
        show: AppMainBundle:Page:show.html.twig

parameters:
    assets_version: 1
    kernel.web_dir: "%kernel.root_dir%/../www.technodevice.com.ua/"
