<?php

namespace App\MainBundle\Form;



class Choices
{
    // ([a-zA-Zа-яА-Я0-9\+\-\_\.\/±\(\),\'\* ]+)
    // '$1' => '$1',
    // ™
    protected static $choices = array(
        'bt_class' => array(
            'A++' => 'A++',
            'A+' => 'A+',
            'A' => 'A',
            'B' => 'B',
            'C' => 'C',
            'D' => 'D',
            'E' => 'E',
            'F' => 'F',
            'G' => 'G',
        ),
        'bt_color' => array(
            'К' => 'К',
            'О' => 'О',
            'Ж' => 'Ж',
            'З' => 'З',
            'Г' => 'Г',
            'С' => 'С',
            'Ф' => 'Ф',
        ),
        'climat_freon_mark' => array(
            'R407c' => 'R407c',
            'R507a' => 'R507a',
            'R404' => 'R404',
            'R410a' => 'R410a',
            'R134a' => 'R134a',
        ),
        'climat_type' => array(
            'Вентиляторы' => 'Вентиляторы',
            'Водонагреватели' => 'Водонагреватели',
            'Керамические обогреватели' => 'Керамические обогреватели',
            'Конвекторы' => 'Конвекторы',
            'Кондиционеры' => 'Кондиционеры',
            'Масляные обогреватели' => 'Масляные обогреватели',
            'Метеостанции' => 'Метеостанции',
            'Сплит-система' => 'Сплит-система',
            'Тепловентеляторы' => 'Тепловентеляторы',
        ),
        'sss' => array(
            'Охлаждение' => 'Охлаждение',
            'Обогрев' => 'Обогрев',
            'Осушение' => 'Осушение',
            'Вентиляция' => 'Вентиляция',
        ),
        'cpu_socket' => array(
            'AM3' => 'AM3',
            'AM3+' => 'AM3+',
            'FM1' => 'FM1',
            'FM2' => 'FM2',
            's1150' => 's1150',
            's1155' => 's1155',
            's2011' => 's2011',
            's775' => 's775',
        ),
        'cpu_family' => array(
            'Intel Core™2 Duo' => 'Intel Core™2 Duo',
            'Intel Core ™ i7' => 'Intel Core ™ i7',
            'Intel Core ™ i5' => 'Intel Core ™ i5',
            'Intel Core ™ i3' => 'Intel Core ™ i3',
            'Intel Pentium' => 'Intel Pentium',
            'Intel Celeron' => 'Intel Celeron',
            'AMD FX-Series' => 'AMD FX-Series',
            'AMD A-Series' => 'AMD A-Series',
            'AMD Phenom™ II' => 'AMD Phenom™ II',
            'AMD Athlon™ II' => 'AMD Athlon™ II',
            'AMD Sempron' => 'AMD Sempron',
        ),
        'ram_ram_type' => array(
            'DDR' => 'DDR',
            'DDR 2' => 'DDR 2',
            'DDR 3' => 'DDR 3',
            'SDRAM' => 'SDRAM',
            'Для настольного компьютера' => 'Для настольного компьютера',
            'Для ноутбука' => 'Для ноутбука',
            'Для Apple' => 'Для Apple',
        ),
        'ram_frequency' => array(
            '133 MHz' => '133 MHz',
            '333 MHz' => '333 MHz',
            '533 MHz' => '533 MHz',
            '400 MHz' => '400 MHz',
            '667 MHz' => '667 MHz',
            '800 MHz' => '800 MHz',
            '1066 MHz' => '1066 MHz',
            '1333 MHz' => '1333 MHz',
            '1600 MHz' => '1600 MHz',
            '1866 MHz' => '1866 MHz',
            '2000 MHz' => '2000 MHz',
            '2133 MHz' => '2133 MHz',
            '2400 MHz' => '2400 MHz',
            '2600 MHz' => '2600 MHz',
            '2666 MHz' => '2666 MHz',
            '2800 MHz' => '2800 MHz',
        ),
        'gpu_chipset' => array(
            'GeForce другие' => 'GeForce другие',
            'GeForce GT 600 серия' => 'GeForce GT 600 серия',
            'GeForce GT 200 серия' => 'GeForce GT 200 серия',
            'GeForce GT 400 серия' => 'GeForce GT 400 серия',
            'GeForce GT 500 серия' => 'GeForce GT 500 серия',
            'GeForce GTS серия' => 'GeForce GTS серия',
            'GeForce GTX 500 серия' => 'GeForce GTX 500 серия',
            'GeForce GTX 600 серия' => 'GeForce GTX 600 серия',
            'GeForce GTX 700 серия' => 'GeForce GTX 700 серия',
            'Radeon HD 5000 серия' => 'Radeon HD 5000 серия',
            'Radeon HD 6000 серия' => 'Radeon HD 6000 серия',
            'Radeon HD 7000 серия' => 'Radeon HD 7000 серия',
        ),
        'gpu_ram_size' => array(
            '128 MB - 1024 Mb' => '128 MB - 1024 Mb',
            '1280 Mb - 6144 Mb' => '1280 Mb - 6144 Mb',
        ),
        'gpu_ram_type' => array(
            'DDR' => 'DDR',
            'DDR II' => 'DDR II',
            'DDR III' => 'DDR III',
            'GDDR 5' => 'GDDR 5',
        ),
        'gpu_bit' => array(
            '32 Bit - 256 Bit' => '32 Bit - 256 Bit',
            '320 Bit - 512 Bit' => '320 Bit - 512 Bit',
        ),
        'gpu_cool' => array(
            'Активное' => 'Активное',
            'Пассивное' => 'Пассивное',
        ),
        'gpu_interface' => array(
            'PCI-Express' => 'PCI-Express',
            'AGP' => 'AGP',
        ),
        'hdd_buffer' => array(
            '8 MB - 32 MB' => '8 MB - 32 MB',
            '64 MB - 128 MB' => '64 MB - 128 MB',
        ),
        'hdd_interface' => array(
            'IDE' => 'IDE',
            'SATA' => 'SATA',
            'SATA II' => 'SATA II',
            'SATA III' => 'SATA III',
        ),
        'sdd_size' => array(
            'до 500 GB' => 'до 500 GB',
            'свыше 500 GB' => 'свыше 500 GB',
        ),
        'sdd_interface' => array(
            'USB 3.0' => 'USB 3.0',
            'SATA II' => 'SATA II',
            'SATA III' => 'SATA III',
            'mSATA' => 'mSATA',
        ),
        'sdd_read' => array(
            'до 200 Mb/s' => 'до 200 Mb/s',
            '200-500Mb/s' => '200-500Mb/s',
            'свыше 500Mb/s' => 'свыше 500Mb/s',
        ),
        'sdd_speed' => array(
            'до 200 Mb/s' => 'до 200 Mb/s',
            '200-500Mb/s' => '200-500Mb/s',
            'свыше 500Mb/s' => 'свыше 500Mb/s',
        ),
        'odd_class' => array(
            'Blu-Ray/HD-DVD' => 'Blu-Ray/HD-DVD',
            'DVD±RW' => 'DVD±RW',
        ),
        'odd_interface' => array(
            'SATA' => 'SATA',
            'USB 2.0' => 'USB 2.0',
            'USB 3.0' => 'USB 3.0',
        ),
        'odd_color' => array(
            'белый' => 'белый',
            'серебристый' => 'серебристый',
            'черный' => 'черный',
            'черный+серебристый' => 'черный+серебристый',
        ),
        'mb_proc' => array(
            'AMD' => 'AMD',
            'INTEL' => 'INTEL',
        ),
        'mb_socket' => array(
            'Socket 754' => 'Socket 754',
            'Socket 775' => 'Socket 775',
            'Socket 939' => 'Socket 939',
            'Socket 1150' => 'Socket 1150',
            'Socket 1155' => 'Socket 1155',
            'Socket 1156' => 'Socket 1156',
            'Socket 2011' => 'Socket 2011',
            'Socket AM2' => 'Socket AM2',
            'Socket AM3' => 'Socket AM3',
            'Socket AM3+' => 'Socket AM3+',
            'Socket FM1' => 'Socket FM1',
            'Socket FM2' => 'Socket FM2',
            'С встроенным процессором' => 'С встроенным процессором',
        ),
        'mb_chipset' => array(
            'AMD 760G' => 'AMD 760G',
            'AMD 770' => 'AMD 770',
            'AMD 780G' => 'AMD 780G',
            'AMD 785G' => 'AMD 785G',
            'AMD 880G' => 'AMD 880G',
            'AMD 970' => 'AMD 970',
            'AMD 990FX' => 'AMD 990FX',
            'AMD 990X' => 'AMD 990X',
            'AMD A45' => 'AMD A45',
            'AMD A50M' => 'AMD A50M',
            'AMD A75' => 'AMD A75',
            'AMD A85X' => 'AMD A85X',
            'AMD A55 FCH (Hudson D2)' => 'AMD A55 FCH (Hudson D2)',
            'AMD A75 FCH (Hudson D3)' => 'AMD A75 FCH (Hudson D3)',
            'AMD A85X FCH(Hudson D4)' => 'AMD A85X FCH(Hudson D4)',
            'Intel HM70' => 'Intel HM70',
            'Intel B75' => 'Intel B75',
            'Intel C202' => 'Intel C202',
            'Intel C216' => 'Intel C216',
            'Intel G41' => 'Intel G41',
            'Intel H55' => 'Intel H55',
            'Intel H61' => 'Intel H61',
            'Intel H61 (B3)' => 'Intel H61 (B3)',
            'Intel H81' => 'Intel H81',
            'Intel P67 (B3)' => 'Intel P67 (B3)',
            'Intel H67' => 'Intel H67',
            'Intel H67 (B3)' => 'Intel H67 (B3)',
            'Intel H77' => 'Intel H77',
            'Intel NM10' => 'Intel NM10',
            'Intel NM70' => 'Intel NM70',
            'Intel P67' => 'Intel P67',
            'Intel Q67' => 'Intel Q67',
            'Intel Q77' => 'Intel Q77',
            'Intel X79' => 'Intel X79',
            'Intel Z68' => 'Intel Z68',
            'Intel Z75' => 'Intel Z75',
            'Intel B85' => 'Intel B85',
            'Intel H87' => 'Intel H87',
            'Intel Z77' => 'Intel Z77',
            'Intel Z87' => 'Intel Z87',
            'GF 6150' => 'GF 6150',
            'GF 7025' => 'GF 7025',
            'NF 720D' => 'NF 720D',
            'NF3 250' => 'NF3 250',
        ),
        'mb_memory' => array(
            'DDR3' => 'DDR3',
            'DDR' => 'DDR',
            'DDR2' => 'DDR2',
            'DDR2+DDR3' => 'DDR2+DDR3',
            'DDR3 SoDimm' => 'DDR3 SoDimm',
        ),
        'box_class' => array(
            'Геймерские' => 'Геймерские',
            'Для неттопов' => 'Для неттопов',
            'Классические' => 'Классические',
            'Компактные' => 'Компактные',
            'Мультимедийные' => 'Мультимедийные',
            'Серверные' => 'Серверные',
        ),
        'box_form' => array(
            'XL-ATX' => 'XL-ATX',
            'EATX' => 'EATX',
            'ATX' => 'ATX',
            'micro-ATX' => 'micro-ATX',
            'Mini-ITX' => 'Mini-ITX',
            'Mini-ITX, m.ATX' => 'Mini-ITX, m.ATX',
        ),
        'box_power' => array(
            'до 400 Вт' => 'до 400 Вт',
            'свыше 400 Вт' => 'свыше 400 Вт',
            'без блока питания' => 'без блока питания',
        ),
        'box_inputs' => array(
            'USB 2.0' => 'USB 2.0',
            'USB 3.0' => 'USB 3.0',
            'FireWire' => 'FireWire',
            'eSATA' => 'eSATA',
            'Audio' => 'Audio',
        ),
        'bp_power' => array(
            'до 500Вт' => 'до 500Вт',
            'свыше 500Вт' => 'свыше 500Вт',
        ),
        'bp_cooler' => array(
            '40 мм - 80 мм' => '40 мм - 80 мм',
            '120 мм - 140 мм' => '120 мм - 140 мм',
            'Без вентилятора' => 'Без вентилятора',
        ),
        'fusb_type' => array(
            'Классические' => 'Классические',
            'С выдвижным USB' => 'С выдвижным USB',
            'Суперкомпактные' => 'Суперкомпактные',
            'Высокоскоростные' => 'Высокоскоростные',
            'Повышенная защита корпуса' => 'Повышенная защита корпуса',
            'Оригинальное оформление' => 'Оригинальное оформление',
            'Стильные и гламурные' => 'Стильные и гламурные',
            'В металлическом корпусе' => 'В металлическом корпусе',
            'С защитой информации' => 'С защитой информации',
        ),
        'fusb_size' => array(
            '4 Gb' => '4 Gb',
            '8 Gb' => '8 Gb',
            '16 Gb' => '16 Gb',
            '32 Gb' => '32 Gb',
            '128 Gb' => '128 Gb',
            '64 Gb' => '64 Gb',
        ),
        'fusb_size' => array(
            'USB 2.0' => 'USB 2.0',
            'USB 3.0' => 'USB 3.0',
        ),
        'fusb_material' => array(
            'Кожа' => 'Кожа',
            'Металл' => 'Металл',
            'Пластик' => 'Пластик',
            'Резина' => 'Резина',
        ),
        'key_type' => array(
            'Классические' => 'Классические',
            'Мультимедийные' => 'Мультимедийные',
            'Геймерские' => 'Геймерские',
            'Беспроводные' => 'Беспроводные',
            'Компактные' => 'Компактные',
            'Числовые' => 'Числовые',
            'С подсветкой' => 'С подсветкой',
            'Тонкие' => 'Тонкие',
            'Нестандартные' => 'Нестандартные',
        ),
        'key_connection' => array(
            'Беспроводная' => 'Беспроводная',
            'Проводная' => 'Проводная',
        ),
        'key_connection_interface' => array(
            'Bluetooth' => 'Bluetooth',
            'PS/2' => 'PS/2',
            'USB' => 'USB',
            'USB+PS/2' => 'USB+PS/2',
            'радио интерфейс' => 'радио интерфейс',
        ),
        'mouse_sensor_type' => array(
            'BlueTrack' => 'BlueTrack',
            'V-Laser (технология V-Track)' => 'V-Laser (технология V-Track)',
            'Инфракрасный' => 'Инфракрасный',
            'Лазерный' => 'Лазерный',
            'Оптическая' => 'Оптическая',
        ),
        'mouse_connection_type' => array(
            'беспроводной (Bluetooth)' => 'беспроводной (Bluetooth)',
            'беспроводной (Wi-Fi)' => 'беспроводной (Wi-Fi)',
            'беспроводной (радио)' => 'беспроводной (радио)',
            'гибридная система радио/ проводная' => 'гибридная система радио/ проводная',
            'проводная' => 'проводная',
            'с выдвигающимся шнуром' => 'с выдвигающимся шнуром',
        ),
        'mouse_connection_interface' => array(
            'Bluetooth' => 'Bluetooth',
            'PS/2' => 'PS/2',
            'PS/2 + USB' => 'PS/2 + USB',
            'USB' => 'USB',
            'Wi-Fi' => 'Wi-Fi',
            'радио интерфейс' => 'радио интерфейс',
        ),
        'pad_class' => array(
            'Начального уровня' => 'Начального уровня',
            'Оптимальные' => 'Оптимальные',
            'Мультимедийный центр' => 'Мультимедийный центр',
            'Смартфон+Планшет' => 'Смартфон+Планшет',
            'З 4G-модемом' => 'З 4G-модемом',
            'Игровые nVidia' => 'Игровые nVidia',
            'С 3G-модемом' => 'С 3G-модемом',
            'С 3G-модемом, Dual SIM' => 'С 3G-модемом, Dual SIM',
            'С GPS-приемником' => 'С GPS-приемником',
            'С док-станцией' => 'С док-станцией',
            'С клавиатурой' => 'С клавиатурой',
        ),
        'pad_size' => array(
            "До 7'" => "До 7'",
            "7' - 7.7'" => "7' - 7.7'",
            "8' - 8.9'" => "8' - 8.9'",
            "9' - 9.7'" => "9' - 9.7'",
            "10' - 11'" => "10' - 11'",
            "Больше 11'" => "Больше 11'",
        ),
        'pad_proc' => array(
            'Apple A6' => 'Apple A6',
            'Boxchip' => 'Boxchip',
            'Intel Celeron' => 'Intel Celeron',
            'Intel Core i3' => 'Intel Core i3',
            'Rockchip' => 'Rockchip',
            'AMD' => 'AMD',
            'Apple A5' => 'Apple A5',
            'ARM Cortex' => 'ARM Cortex',
            'Intel Atom' => 'Intel Atom',
            'NVIDIA Tegra' => 'NVIDIA Tegra',
            'Qualcomm Snapdragon' => 'Qualcomm Snapdragon',
        ),
        'pad_memory_ram' => array(
            '512Mb' => '512Mb',
            '1Gb' => '1Gb',
            '2Gb' => '2Gb',
            '4Gb' => '4Gb',
        ),
        'pad_memory_hdd' => array(
            '4 Gb' => '4 Gb',
            '8 Gb' => '8 Gb',
            '16 Gb' => '16 Gb',
            '32 Gb' => '32 Gb',
            '64 Gb' => '64 Gb',
            '128Gb' => '128Gb',
        ),
        'pad_os' => array(
            'Windows' => 'Windows',
            'Windows RT' => 'Windows RT',
            'Android' => 'Android',
            'iOS' => 'iOS',
            'Windows + Android' => 'Windows + Android',
        ),
        'pad_wireless' => array(
            "Wi-Fi" => "Wi-Fi",
            "Bluetooth" => "Bluetooth",
            "3G" => "3G",
            "4G" => "4G",
        ),
        'printer_functions' => array(
            "3 в одном" => "3 в одном",
            "4 в одном" => "4 в одном",
        ),
        'printer_print_technology' => array(
            "Лазерная" => "Лазерная",
            "Струйная" => "Струйная",
        ),
        'printer_print_colors' => array(
            "цветная(4 цвета)" => "цветная(4 цвета)",
            "цветная (5 цветов)" => "цветная (5 цветов)",
            "цветная (6 цветов)" => "цветная (6 цветов)",
            "монохромная" => "монохромная",
        ),
        'printer_print_format' => array(
            "До А3" => "До А3",
            "До А4" => "До А4",
        ),
        'printer_print_speed_mono' => array(
            "10 - 20 стр/мин" => "10 - 20 стр/мин",
            "21 - 30 стр/мин" => "21 - 30 стр/мин",
            "31 - 40 стр/мин " => "31 - 40 стр/мин ",
            "более 40 стр/мин" => "более 40 стр/мин",
        ),
        'printer_print_speed_color' => array(
            "10 - 20 стр/мин" => "10 - 20 стр/мин",
            "21 - 30 стр/мин" => "21 - 30 стр/мин",
            "31 - 40 стр/мин" => "31 - 40 стр/мин",
        ),
        'printer_interface' => array(
            "USB" => "USB",
            "Ethernet" => "Ethernet",
            "Bluetooth" => "Bluetooth",
            "WiFi" => "WiFi",
        ),
        'router_speed' => array(
            "до 1300Mbps" => "до 1300Mbps",
            "до 150Mbps" => "до 150Mbps",
            "до 300Mbps" => "до 300Mbps",
            "до 450Mbps" => "до 450Mbps",
            "до 54Mbps" => "до 54Mbps",
            "до 600Mbps" => "до 600Mbps",
            "до 750Mbps" => "до 750Mbps",
        ),
        'router_wifi' => array(
            "802.11 n/g" => "802.11 n/g",
            "802.11 n/g/a" => "802.11 n/g/a",
            "802.11 n/g/a/ac" => "802.11 n/g/a/ac",
            "IEEE 802.11 g" => "IEEE 802.11 g",
        ),
        'web_adapter_class' => array(
            "до 600 В*А" => "до 600 В*А",
            "от 601 до 1000 В*А" => "от 601 до 1000 В*А",
            "от 1001 до 2000 В*А" => "от 1001 до 2000 В*А",
            "более 2001 В*А" => "более 2001 В*А",
        ),
        'web_adapter_cart' => array(
            "до 400 Вт" => "до 400 Вт",
            "от 401 до 600 Вт" => "от 401 до 600 Вт",
            "от 601 до 1000 Вт" => "от 601 до 1000 Вт",
            "от 1001 до 1500 Вт" => "от 1001 до 1500 Вт",
            "более 1501 Вт" => "более 1501 Вт",
        ),
//        'sss' => array(
//        ),
    );

    public static function get($key)
    {
        return isset(self::$choices[$key]) ? self::$choices[$key] : array();
    }
}