app_main_cart_additem:
    pattern: /items
    methods: [POST]
    defaults:
        _controller: app.controller.cart_item:addAction

app_main_cart_deleteitem:
    pattern: /items/{id}/delete
    methods: [GET]
    defaults:
        _controller: app.controller.cart_item:deleteAction
        _sylius:
            redirect:
                route: app_main_cart_list
                parameters: { id: $id }

app_main_cart_list:
    pattern: /
    methods: [GET]
    defaults:
        _controller: app.controller.cart:listAction

app_main_cart_save:
    pattern: /save
    methods: [POST]
    defaults:
        _controller: app.controller.cart:saveAction
