app_main_mention_create:
    pattern: /create/{id}
    methods: [POST]
    defaults:
        _controller: app.controller.mention:createAction

app_main_mention_form:
    pattern: /form/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.mention:formAction
        _sylius:
            template: AppMainBundle:Mention:_form.html.twig
