app_main_product_show:
    pattern: /product/{id}
    methods: [GET]
    defaults:
        _controller: app.controller.product:showAction
        _sylius:
            template: AppMainBundle:Product:show.html.twig
            criteria:
                id: $id

app_main_product_list:
    pattern: /category/{id}/products
    methods: [GET]
    defaults:
        _controller: app.controller.product:listAction
        _sylius:
            paginate: 30
