rid_image:
    dir:
        web: %kernel.web_dir%
    presets:
        categoryImage:
            path: uploads/category/
            thumbnails:
                mid:
                    default: img/def-category-mid.png
                    width: 305
                    height: 180
                    type: outbound
        productImage:
            path: uploads/product/
            thumbnails:
                mid:
                    default: img/def-product-mid.png
                    width: 200
                    height: 140
                    type: outbound
                show:
                    default: img/def-product-show.png
                    width: 280
                    height: 195
                    type: outbound
                tiny:
                    default: img/def-product-tiny.png
                    width: 60
                    height: 35
                    type: outbound
                cart:
                    default: img/def-product-cart.png
                    width: 160
                    height: 110
                    type: outbound


        slideImage:
            path: uploads/slider/
            thumbnails:
                mid:
                    width: 640
                    height: 205
                    type: outbound

        actionImage:
            path: uploads/action/
            thumbnails:
                mid:
                    width: 280
                    height: 400
                    type: outbound

    fields:
        App\MainBundle\Entity\Category:
            image: categoryImage
        App\MainBundle\Entity\Product:
            image: productImage
            image2: productImage
            image3: productImage
            image4: productImage
        App\MainBundle\Entity\Slide:
            image: slideImage
        App\MainBundle\Entity\Action:
            image: actionImage