rid_image:
    presets:
        categoryImage:
            path: uploads/category/
            thumbnails:
                mid:
                    width: 305
                    height: 180
                    type: outbound
        productImage:
            path: uploads/product/
            thumbnails:
                mid:
                    width: 200
                    height: 140
                    type: outbound

    fields:
        App\MainBundle\Entity\Category:
            image: categoryImage
        App\MainBundle\Entity\Product:
            image: productImage