sonata_admin:
    title:      Админ панель
    options:
        use_select2: false
        confirm_exit:   false # disable confirmation when quitting with unsaved changes
    templates:
         layout:  AppAdminBundle::standard_layout.html.twig
         dashboard: AppAdminBundle::dashboard.html.twig
#    dashboard:
#        groups:
#            group_name:
#                label: " "
#                items: ~
