sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title: Интернет магазин бытовой техники Технодевайс Черкассы | technodevice.com.ua
        metas:
            name:
                keywords: интернет-магазин для всей семьи в городе Черкассы
                description: 093 731-85-03 | Современный интернет-магазин для всей семьи в городе Черкассы
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       technodevice.com.ua
                'og:description':     093 731-85-03 | Современный интернет-магазин для всей семьи в городе Черкассы

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"