sonata_admin:
    templates:
         layout:  AppAdminBundle::standard_layout.html.twig
#    dashboard:
#        groups:
#            group_name:
#                label: " "
#                items: ~
