sylius_resource:
    resources:
        app.category:
            driver: doctrine/orm
            templates: AppMainBundle:Category
            classes:
                model: App\MainBundle\Entity\Category
                repository: App\MainBundle\Entity\CategoryRepository

        app.product:
            driver: doctrine/orm
            templates: AppMainBundle:Product
            classes:
                model: App\MainBundle\Entity\Product
                controller: App\MainBundle\Controller\ProductController
                repository: App\MainBundle\Entity\ProductRepository

        app.property:
            driver: doctrine/orm
            templates: AppMainBundle:Property
            classes:
                model: App\MainBundle\Entity\Property

        app.prototype:
            driver: doctrine/orm
            templates: AppMainBundle:Prototype
            classes:
                model: App\MainBundle\Entity\Prototype
                repository: App\MainBundle\Entity\PrototypeRepository

        app.cart:
            driver: doctrine/orm
            templates: AppMainBundle:Cart
            classes:
                controller: App\MainBundle\Controller\CartController
                model: App\MainBundle\Entity\Cart
                repository: App\MainBundle\Entity\CartRepository

        app.cart_item:
            driver: doctrine/orm
            templates: AppMainBundle:CartItem
            classes:
                controller: App\MainBundle\Controller\CartItemController
                model: App\MainBundle\Entity\CartItem

        app.slide:
            driver: doctrine/orm
            templates: AppMainBundle:Slide
            classes:
                model: App\MainBundle\Entity\Slide

        app.order:
            driver: doctrine/orm
            templates: AppMainBundle:Order
            classes:
                controller: App\MainBundle\Controller\OrderController
                model: App\MainBundle\Entity\Order

        app.mention:
            driver: doctrine/orm
            templates: AppMainBundle:Mention
            classes:
                model: App\MainBundle\Entity\Mention