app_main_homepage:
    pattern:  /
    defaults: { _controller: AppMainBundle:Default:index }

_app_main_category:
    prefix:  /category
    resource: 'routing/category.yml'

_app_main_product:
    prefix:  /product
    resource: 'routing/product.yml'

_app_main_cart:
    prefix:  /cart
    resource: 'routing/cart.yml'