parameters:
#    app_main.example.class: App\MainBundle\Example

services:
#forms
    app.main.form_type.order:
        class: App\MainBundle\Form\OrderType
        tags:
            - { name: form.type, alias: app_order }

    app.main.form_type.product_property:
        class: App\MainBundle\Form\ProductPropertyType
        tags:
            - { name: form.type, alias: app_product_property }
#services
    app.main.services.xls_import:
        class: App\MainBundle\Services\XlsImport
        calls:
            - [ setProductRepository, [ @app.repository.product ] ]
            - [ setCategoryRepository, [ @app.repository.category ] ]
            - [ setPrototypeRepository, [ @app.repository.prototype ] ]
            - [ setEm, [ @doctrine.orm.entity_manager ] ]
            - [ setWebPath, [ %kernel.web_dir% ] ]
            - [ setRedis, [ @snc_redis.default ]]

    app.main.services.cart_manager:
        class: App\MainBundle\Services\CartManager
        calls:
            - [ setRepository, [ @app.repository.cart ] ]
            - [ setSession, [ @session ] ]
            - [ setEm, [ @doctrine.orm.entity_manager ] ]

    app.main.services.twig_extension.app:
        class: App\MainBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setCartManager, [ @app.main.services.cart_manager ] ]

    app.main.services.product_filter:
        class: App\MainBundle\Services\ProductFilter
        calls:
            - [ setRepository, [ @app.repository.product ] ]

    app.main.services.redirect_q:
        class: App\MainBundle\Services\RedirectQ
        calls:
            - [ setSession, [ @session ] ]

    app.main.security.success_handler:
        class: App\MainBundle\Services\Security\LoginHandler
        calls:
            - [ setRedirectQ, [ @app.main.services.redirect_q ] ]
            - [ setRouting, [ @router ] ]

    app.main.security.subscriber:
        class: App\MainBundle\Services\Security\Subscriber
        calls:
            - [ setRedirectQ, [ @app.main.services.redirect_q ] ]
        tags:
            - { name: kernel.event_subscriber }

    app.main.entity_listener:
        class: App\MainBundle\EntityListener\EntityListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }