parameters:
#    app_main.example.class: App\MainBundle\Example

services:
#    app_main.example:
#        class: %app_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
